"""init db

Revision ID: 0a2a5bb379a4
Revises: 
Create Date: 2021-08-27 16:44:42.469339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a2a5bb379a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('parent_name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_deleted'), 'department', ['deleted'], unique=False)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=False)
    op.create_table('document_type',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_type_created_at'), 'document_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_type_deleted'), 'document_type', ['deleted'], unique=False)
    op.create_index(op.f('ix_document_type_name'), 'document_type', ['name'], unique=False)
    op.create_table('permission',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=250), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_created_at'), 'permission', ['created_at'], unique=False)
    op.create_index(op.f('ix_permission_deleted'), 'permission', ['deleted'], unique=False)
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=False)
    op.create_table('position',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('parent_name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_created_at'), 'position', ['created_at'], unique=False)
    op.create_index(op.f('ix_position_deleted'), 'position', ['deleted'], unique=False)
    op.create_index(op.f('ix_position_name'), 'position', ['name'], unique=False)
    op.create_table('unit',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_created_at'), 'unit', ['created_at'], unique=False)
    op.create_index(op.f('ix_unit_deleted'), 'unit', ['deleted'], unique=False)
    op.create_index(op.f('ix_unit_name'), 'unit', ['name'], unique=False)
    op.create_table('user_role',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_created_at'), 'user_role', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_role_deleted'), 'user_role', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_role_name'), 'user_role', ['name'], unique=False)
    op.create_table('document',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('code', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('sign_day', sa.BigInteger(), nullable=True),
    sa.Column('signer', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.Column('end_at', sa.BigInteger(), nullable=True),
    sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('unit_name', sa.String(length=250), nullable=True),
    sa.Column('document_type_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('document_type_name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_created_at'), 'document', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_deleted'), 'document', ['deleted'], unique=False)
    op.create_index(op.f('ix_document_name'), 'document', ['name'], unique=False)
    op.create_table('document_expires',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('unit_name', sa.String(length=250), nullable=True),
    sa.Column('document_type_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('document_type_name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_expires_created_at'), 'document_expires', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_expires_deleted'), 'document_expires', ['deleted'], unique=False)
    op.create_table('staff',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('position_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('position_name', sa.String(length=250), nullable=True),
    sa.Column('department_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('department_name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_code'), 'staff', ['code'], unique=False)
    op.create_index(op.f('ix_staff_deleted'), 'staff', ['deleted'], unique=False)
    op.create_table('user_role_permission',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('user_role_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('permission_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_permission_created_at'), 'user_role_permission', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_role_permission_deleted'), 'user_role_permission', ['deleted'], unique=False)
    op.create_table('account',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('role_name', sa.String(length=250), nullable=True),
    sa.Column('staff_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('staff_name', sa.String(length=250), nullable=True),
    sa.Column('staff_code', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_created_at'), 'account', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_deleted'), 'account', ['deleted'], unique=False)
    op.create_index(op.f('ix_account_password'), 'account', ['password'], unique=False)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_table('department_document',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('document_name', sa.String(length=250), nullable=True),
    sa.Column('document_type_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('department_name', sa.String(length=250), nullable=True),
    sa.Column('department_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_document_created_at'), 'department_document', ['created_at'], unique=False)
    op.create_index(op.f('ix_department_document_deleted'), 'department_document', ['deleted'], unique=False)
    op.create_table('staff_document',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('staff_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('staff_name', sa.String(length=250), nullable=True),
    sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('document_name', sa.String(length=250), nullable=True),
    sa.Column('document_type_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_document_created_at'), 'staff_document', ['created_at'], unique=False)
    op.create_index(op.f('ix_staff_document_deleted'), 'staff_document', ['deleted'], unique=False)
    op.create_table('work_report',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=500), nullable=False),
    sa.Column('review_description', sa.String(length=500), nullable=True),
    sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('document_name', sa.String(length=250), nullable=True),
    sa.Column('staff_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('staff_name', sa.String(length=250), nullable=True),
    sa.Column('staff_code', sa.String(length=250), nullable=True),
    sa.Column('department_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('department_name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_report_created_at'), 'work_report', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_report_deleted'), 'work_report', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_report_deleted'), table_name='work_report')
    op.drop_index(op.f('ix_work_report_created_at'), table_name='work_report')
    op.drop_table('work_report')
    op.drop_index(op.f('ix_staff_document_deleted'), table_name='staff_document')
    op.drop_index(op.f('ix_staff_document_created_at'), table_name='staff_document')
    op.drop_table('staff_document')
    op.drop_index(op.f('ix_department_document_deleted'), table_name='department_document')
    op.drop_index(op.f('ix_department_document_created_at'), table_name='department_document')
    op.drop_table('department_document')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_password'), table_name='account')
    op.drop_index(op.f('ix_account_deleted'), table_name='account')
    op.drop_index(op.f('ix_account_created_at'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_role_permission_deleted'), table_name='user_role_permission')
    op.drop_index(op.f('ix_user_role_permission_created_at'), table_name='user_role_permission')
    op.drop_table('user_role_permission')
    op.drop_index(op.f('ix_staff_deleted'), table_name='staff')
    op.drop_index(op.f('ix_staff_code'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_document_expires_deleted'), table_name='document_expires')
    op.drop_index(op.f('ix_document_expires_created_at'), table_name='document_expires')
    op.drop_table('document_expires')
    op.drop_index(op.f('ix_document_name'), table_name='document')
    op.drop_index(op.f('ix_document_deleted'), table_name='document')
    op.drop_index(op.f('ix_document_created_at'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_user_role_name'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_deleted'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_created_at'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_unit_name'), table_name='unit')
    op.drop_index(op.f('ix_unit_deleted'), table_name='unit')
    op.drop_index(op.f('ix_unit_created_at'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_position_name'), table_name='position')
    op.drop_index(op.f('ix_position_deleted'), table_name='position')
    op.drop_index(op.f('ix_position_created_at'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_index(op.f('ix_permission_deleted'), table_name='permission')
    op.drop_index(op.f('ix_permission_created_at'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_document_type_name'), table_name='document_type')
    op.drop_index(op.f('ix_document_type_deleted'), table_name='document_type')
    op.drop_index(op.f('ix_document_type_created_at'), table_name='document_type')
    op.drop_table('document_type')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_index(op.f('ix_department_deleted'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
