"""update db

Revision ID: 0bbd49d8f95c
Revises: a74c9e752575
Create Date: 2021-10-20 21:07:06.091543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbd49d8f95c'
down_revision = 'a74c9e752575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'staff_code')
    op.drop_column('account', 'staff_name')
    op.drop_column('account', 'role_name')
    op.drop_column('department_document', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_document', sa.Column('status', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('role_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('staff_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('staff_code', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
