"""update dba

Revision ID: 3dbe0d78b4dd
Revises: c5d1cea0804d
Create Date: 2021-11-30 21:21:47.624724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbe0d78b4dd'
down_revision = 'c5d1cea0804d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
