"""update db

Revision ID: 639bb5e76989
Revises: 2bcb92201149
Create Date: 2021-11-20 09:24:07.032380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639bb5e76989'
down_revision = '2bcb92201149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
