"""update db

Revision ID: a74c9e752575
Revises: 69b3c747dab7
Create Date: 2021-10-19 08:14:11.537319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74c9e752575'
down_revision = '69b3c747dab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'slug')
    # ### end Alembic commands ###
