"""update db

Revision ID: c5b25c4e4cbe
Revises: 0bbd49d8f95c
Create Date: 2021-10-21 10:59:00.925599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b25c4e4cbe'
down_revision = '0bbd49d8f95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('staff_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'staff_name')
    # ### end Alembic commands ###
