"""update db

Revision ID: eee58152541b
Revises: 639bb5e76989
Create Date: 2021-11-30 21:17:31.152274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee58152541b'
down_revision = '639bb5e76989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
