"""update db

Revision ID: f12a07319111
Revises: 95ad4f003ca7
Create Date: 2021-11-01 15:03:31.634713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12a07319111'
down_revision = '95ad4f003ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
